### ISSUE TITLE
install sissue

### ISSUE THREAD

**Issue by SinisterY88** [mplutka/tm-bt-led#4]
Hi Markus! would appreciate any help you can provide. 

Similar to the other user, I have experienced install issues. I have the latest version of the programs stated in the readme file (e.g. nodejs, Python3, etc.).

As you had noted in 2.7.2 readme file, there is no install.bat file but there is a setup.bat file. I get the following errors when trying to run in cmd prompt:

C:\Users\conta\Dropbox\My PC (LAPTOP-BIVJPMN7)\Documents\2.7.2>setup
internal/modules/cjs/loader.js:1127
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: \\?\C:\Users\conta\Dropbox\My PC\Documents\2.7.2\node_modules\usb\build\Release\usb_bindings.node is not a valid Win32 application.
\\?\C:\Users\conta\Dropbox\My PC\Documents\2.7.2\node_modules\usb\build\Release\usb_bindings.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1127:18)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (C:\Users\conta\Dropbox\My PC\Documents\2.7.2\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\Users\conta\Dropbox\My PC\Documents\2.7.2\node_modules\usb\usb.js:1:57)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)

So, i found  "tm-bt-led-master" that was linked somewhere in your documentation (i can't remember where). It does have the install.bat file. So tried to give that a go.

Here is what I get when in cmd prompt with admin access within the unzipped tm-bt-led-master folder:
npm WARN prepare removing existing node_modules/ before installation
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/mplutka/noble.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

I get the same set of errors when installing using "npm install" for the install.bat file.  

Please help. thnx

**Comment by mplutka** [comment]
Hi,
you don‘t need install.bat if you download the prebuilt version from here: https://github.com/mplutka/tm-bt-led/releases/download/2.7.2/2.7.2.zip

just unzip and run setup.bat
Please post the output if this still doesn’t work

**Comment by SinisterY88** [comment]
Thanks Markus, getting the errors as follows when trying to run setup.bat from the unzipped 2.7.2 folder:

C:\Users\Public\Downloads>setup
internal/modules/cjs/loader.js:1127
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: \\?\C:\Users\Public\Downloads\node_modules\usb\build\Release\usb_bindings.node is not a valid Win32 application.
\\?\C:\Users\Public\Downloads\node_modules\usb\build\Release\usb_bindings.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1127:18)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (C:\Users\Public\Downloads\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\Users\Public\Downloads\node_modules\usb\usb.js:1:57)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)

C:\Users\Public\Downloads>

**Comment by mplutka** [comment]
You have most likely installed the 32bit version of nodejs. Please uninstall completely and use this one:
https://nodejs.org/dist/v14.17.0/node-v14.17.0-x64.msi

**Comment by SinisterY88** [comment]
worked like a charm. removed and reinstalled nodejs. Also changed the driver of the BT adapter using zadig before running setup which worked. The only thing is that I need some guidance to set my IP address for forza motorsport 7 so that the BT LED will get UDP info. I saw from the cmd window that your program is listening on 0.0.0.0 however when set to that in forza motorsport 7 the BT LED remains "Thru8stma" on the screen. I think input the IP of the laptop I'm running the game on, e.g. 10.0.0.57 but that didn't work either. Looking for any advice possible (BTW I did read the links you provided for FM7)- thanks Markus.

**Comment by mplutka** [comment]
0.0.0.0 as listening IP means it listens on all available network devices. The IP inside the game must be set to the one of the Laptop/PC my software is running on. Maybe disable any running firewall. That could help.
Also open a cmd window as administrator and enter the following command if you haven't done so already:
CheckNetIsolation.exe LoopbackExempt -a -n=microsoft.apollobasegame_8wekyb3d8bbwe

**Comment by SinisterY88** [comment]
Hi Markus, an update that I ran the command you noted as well as opened port 20127 in the firewall and guess what? FM7 worked! thanks for hanging in there with me. However I will open a separate issue I'm having for Race Room Experience which is a brand new download for me.
